### ISSUE TITLE
Error while Copying Multiple Files 

### ISSUE THREAD

**Issue by SumanRajSharma** [kolyvan/kxsmb#28]
i want to copy multiple files from smb server, But when i loop the 
 [provider copySMBPath:@""  localPath:@"" overwrite:YES block:^(id result) { } some the files fails to copy giving error like  ... Error Domain=error.SMB Code=0 "SMB Error" UserInfo=0x7f8429dd0930 {NSLocalizedDescription=SMB Error, NSLocalizedFailureReason=Unable get stat:smb://192.168.0.1/wifishare/AutoTest Scripts/VIP_ActiveLine.spcv (errno:60)}

but the same file if downloaded individually works fine.

**Comment by ssnhitfkgd** [comment]
overwrite 为no

发自我的 iPhone
