### ISSUE TITLE
rake aborted!  Build failed 

### ISSUE THREAD

**Issue by zyfoolboy** [kolyvan/kxsmb#37]
Hi,
Whenever I am doing "RAKE" from within the kxsmb folder in the terminal I get the following errror:

```
checking whether we are big endian... configure: error: in `/Users/deyi/Downloads/kxsmb/samba/source3':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
rake aborted!
******** Build failed ********
/Users/deyi/Downloads/kxsmb/Rakefile:42:in `system_or_exit'
/Users/deyi/Downloads/kxsmb/Rakefile:216:in `buildArch'
/Users/deyi/Downloads/kxsmb/Rakefile:260:in `block in <top (required)>'
Tasks: TOP => default => build_all => build_smb_i386
(See full trace by running task with --trace)
```

**Comment by borland** [comment]
I have this too, running on macOS 10.12.1 with Xcode 8.0
Any help would be appreciated

**Comment by ppyupp** [comment]
I have this too....
macOS 10.12.2 with Xcode 8.0

**Comment by ppyupp** [comment]
export samba_cv_big_endian=no
export samba_cv_little_endian=yes
export samba_cv_CC_NEGATIVE_ENUM_VALUES=yes
export libreplace_cv_HAVE_GETADDRINFO=yes
export samba_cv_HAVE_WRFILE_KEYTAB=no
export smb_krb5_cv_enctype_to_string_takes_krb5_context_arg=no
export smb_krb5_cv_enctype_to_string_takes_size_t_arg=yes
export ac_cv_file__proc_sys_kernel_core_pattern=yes

rake

**Comment by ppyupp** [comment]
export samba_cv_big_endian=no
export samba_cv_little_endian=yes
export samba_cv_CC_NEGATIVE_ENUM_VALUES=yes
export libreplace_cv_HAVE_GETADDRINFO=no
export samba_cv_HAVE_WRFILE_KEYTAB=no
export smb_krb5_cv_enctype_to_string_takes_krb5_context_arg=no
export smb_krb5_cv_enctype_to_string_takes_size_t_arg=yes
export ac_cv_file__proc_sys_kernel_core_pattern=yes

rake

**Comment by zuozuo1985** [comment]
I have this too, running on macOS 10.12.1 with Xcode 8.0
Any help would be appreciated

**Comment by zyfoolboy** [comment]
I use @ppyupp's method to solve this problem.
Thank you very much!

**Comment by J-DevHouse** [comment]
it's not work @ppyupp 
macOS 10.12.6  with Xcode 9.2,
******** Build failed ********
/Users/jack/Documents/GitHub/kxsmb/Rakefile:42:in `system_or_exit'
/Users/jack/Documents/GitHub/kxsmb/Rakefile:219:in `block in buildArch'
/Users/jack/Documents/GitHub/kxsmb/Rakefile:218:in `each'
/Users/jack/Documents/GitHub/kxsmb/Rakefile:218:in `buildArch'
/Users/jack/Documents/GitHub/kxsmb/Rakefile:243:in `block in <top (required)>'
Tasks: TOP => default => build_all => build_smb_armv7
(See full trace by running task with --trace)
how to do next,thanks
